run:
  tests: false
  timeout: 5m
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - execinquery
    - exportloopref
    - forcetypeassert
    - gocritic
    - gofmt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - nakedret
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
linters-settings:
  gocritic:
    disabled-checks:
      - commentFormatting
