name: CloudFormation Deploy

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
        default: us-east-1
      cloudformation-filename:
        required: true
        type: string
        default: stack.yaml
    secrets:
      deploy-key-id:
        required: true
      deploy-key-value:
        required: true

jobs:
  cloudformation-deploy:
    name: Deploy to AWS CloudFormation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        if: ${{ success() }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.deploy-key-id }}
          aws-secret-access-key: ${{ secrets.deploy-key-value }}
          aws-region: ${{ inputs.aws-region }}

      - name: Deploy to AWS CloudFormation
        if: ${{ success() }}
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ github.event.repository.name }}
          template: ${{ inputs.cloudformation-filename }}
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_NAMED_IAM
