name: CloudFormation Deploy

on:
  workflow_call:
    inputs:
      cloudformation-filename:
        required: false
        type: string
        default: stack.yaml
    secrets:
      deploy-key-id:
        required: true
      deploy-key-value:
        required: true

jobs:
  cloudformation-deploy:
    name: Deploy to AWS CloudFormation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials (production environment)
        if: ${{ success() && startsWith(github.event.repository.name, 'infra-prd-') }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.deploy-key-id }}
          aws-secret-access-key: ${{ secrets.deploy-key-value }}
          aws-region: us-east-1

      - name: Configure AWS Credentials (staging/dev environments)
        if: ${{ success() && (startsWith(github.event.repository.name, 'infra-stg-') }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.deploy-key-id }}
          aws-secret-access-key: ${{ secrets.deploy-key-value }}
          aws-region: us-east-2

      - name: Configure AWS Credentials (sandbox environment)
        if: ${{ success() && (startsWith(github.event.repository.name, 'infra-sbx-') }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.deploy-key-id }}
          aws-secret-access-key: ${{ secrets.deploy-key-value }}
          aws-region: us-west-2

      - name: Deploy to AWS CloudFormation
        if: ${{ success() }}
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ github.event.repository.name }}
          template: ${{ inputs.cloudformation-filename }}
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_NAMED_IAM
