name: CloudFormation Pull Request

on:
  workflow_call:
    secrets:
      github-token:
        required: true

jobs:
  cloudformation-pr-linter:
    uses: Fiinco/github-workflows/.github/workflows/cloudformation_linter.yaml@main

