name: DB Pull Request

on:
  workflow_call:
    secrets:
      github-token:
        required: true

jobs:
  migration_test:
    uses: Fiinco/github-workflows/.github/workflows/db_sql_migration_test.yaml@main
