name: Golang Linter (golang-ci lint)

on:
  workflow_call:
    secrets:
      github-token:
        required: true

env:
  GOPRIVATE: github.com/Fiinco

jobs:
  run-golang-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        if: ${{ success() }}
        with:
          go-version: 1.18
          cache: true

      - run: go version
        if: ${{ success() }}

      - name: Grant access to private Go Modules
        if: ${{ success() }}
        run: git config --global url."https://fiinco:${{ secrets.github-token }}@github.com/Fiinco".insteadOf "https://github.com/Fiinco"

      #- name: Get dependencies
      #  if: ${{ success() }}
      #  run: go mod download

      - uses: golangci/golangci-lint-action@v3
        if: ${{ success() }}
        with:
          version: latest
          skip-pkg-cache: true
          skip-build-cache: true
