name: Golang Pull Request

on:
  workflow_call:
    inputs:
      sql-repository:
        required: false
        type: string
    secrets:
      github-token:
        required: true

jobs:
  golang-pr-linter:
    uses: Fiinco/github-workflows/.github/workflows/golang_linter.yaml@main
    secrets:
      github-token: ${{ secrets.github-token }}

  golang-pr-test-coverage:
    uses: Fiinco/github-workflows/.github/workflows/golang_test_coverage.yaml@main
    with:
      sql-repository: ${{ inputs.sql-repository }}
    secrets:
      github-token: ${{ secrets.github-token }}

  #golang-pr-private-goproxy-test-build:
  #  if: ${{ !startsWith(github.event.repository.name, 'lib-go-') }}
  #  uses: Fiinco/github-workflows/.github/workflows/golang_private_goproxy_test_build.yaml@main
  #  secrets:
  #    github-token: ${{ secrets.github-token }}
