name: Golang Test Coverage

on:
  workflow_call:
    inputs:
      minimum-coverage:
        required: false
        type: string
        default: 1
      go-version:
        required: false
        type: string
        default: 1.18
    secrets:
      github-token:
        required: true

env:
  GOPRIVATE: github.com/Fiinco

jobs:
  golang-test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check if test files exist
        if: ${{ success() }}
        uses: andstor/file-existence-action@v2
        with:
          files: "**/*_test.go"
          fail: true

      - uses: actions/setup-go@v3
        if: ${{ success() }}
        with:
          go-version: ${{ inputs.go-version }}
          cache: true

      - run: go version
        if: ${{ success() }}

      - name: Grant access to private Go Modules
        if: ${{ success() }}
        run: git config --global url."https://fiinco:${{ secrets.github-token }}@github.com/Fiinco".insteadOf "https://github.com/Fiinco"

      - name: Get dependencies
        if: ${{ success() }}
        run: go mod download

      #Go libraries can't be built
      - name: Build Application
        if: ${{ success() && (!startsWith(github.event.repository.name, 'lib-go-')) }}
        run: go build -ldflags="-s -w" -o ./app/ ./...

      - name: Run tests
        if: ${{ success() }}
        run: go test -v -covermode=set -coverprofile=coverage.out ./...

      #No passo de "Grant access to private Go Modules" acima, configuramos o arquivo .git/config com uma informação sensível
      #Vamos limpar as pastas do git para que as actions de agora em diante não tenham acesso àquela informação
      - name: Remove .git directory
        if: ${{ success() }}
        run: rm -r .git

      - name: Convert coverage to lcov
        if: ${{ success() }}
        uses: jandelgado/gcov2lcov-action@v1
        with:
          infile: coverage.out        # optional, default filename is `coverage.out`
          outfile: coverage.lcov      # optional, default filename is `coverage.lcov`

      - name: Check test coverage
        if: ${{ success() }}
        uses: terencetcf/github-actions-lcov-minimum-coverage-checker@v1
        with:
          coverage-file: coverage.lcov
          minimum-coverage: ${{ inputs.minimum-coverage }}


