name: Golang test coverage

on:
  workflow_call:
    secrets:
      github-token:
        required: true

env:
  GOPRIVATE: github.com/Fiinco

jobs:
  golang-test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        if: ${{ success() }}
        with:
          go-version: 1.18
          cache: true

      - run: go version
        if: ${{ success() }}

      - name: Grant access to private Go Modules
        if: ${{ success() }}
        run: git config --global url."https://fiinco:${{ secrets.github-token }}@github.com/Fiinco".insteadOf "https://github.com/Fiinco"

      - name: Get dependencies
        if: ${{ success() }}
        run: go mod download

      - name: Build Application
        if: ${{ success() }}
        run: go build -o ./app ./cmd/main

      - name: Run tests
        if: ${{ success() }}
        run: go test -v -covermode=set -coverprofile=coverage.out ./...

      - name: Convert coverage to lcov
        if: ${{ success() }}
        uses: jandelgado/gcov2lcov-action@v1
        with:
          infile: coverage.out        # optional, default filename is `coverage.out`
          outfile: coverage.lcov      # optional, default filename is `coverage.lcov`

      - name: Check test coverage
        if: ${{ success() }}
        uses: terencetcf/github-actions-lcov-minimum-coverage-checker@v1
        with:
          coverage-file: coverage.lcov
          minimum-coverage: 85


