name: Golang Linter (golang-ci lint)

on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: 1.20
    secrets:
      github-token:
        required: true

env:
  GOPRIVATE: github.com/Fiinco

jobs:
  golang-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        if: ${{ success() }}
        with:
          go-version: ${{ inputs.go-version }}
          cache: true

      - run: go version
        if: ${{ success() }}

      - name: Grant access to private Go Modules
        if: ${{ success() }}
        run: git config --global url."https://fiinco:${{ secrets.github-token }}@github.com/Fiinco".insteadOf "https://github.com/Fiinco"

      - name: Remove any golangci-lint configuration files
        if: ${{ success() }}
        run: rm -f .golangci.yml

      - name: Download Fiinco's official golangci-lint configuration file
        if: ${{ success() }}
        run: wget -O .golangci.yml https://raw.githubusercontent.com/Fiinco/github-workflows/main/.golangci.yml

      - name: Get dependencies
        if: ${{ success() }}
        run: go mod download

      #No passo de "Grant access to private Go Modules" acima, configuramos o arquivo .git/config com uma informação sensível
      #Vamos limpar as pastas do git para que as actions de agora em diante não tenham acesso àquela informação
      - name: Remove .git directory
        if: ${{ success() }}
        run: rm -r .git

      - uses: golangci/golangci-lint-action@v3
        if: ${{ success() }}
        with:
          args: --config .golangci.yml
          version: latest
          skip-pkg-cache: true
          skip-build-cache: true
