name: Golang Private GOPROXY Test Build

on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: '1.20'
    secrets:
      github-token:
        required: true

env:
  GOPRIVATE: github.com/Fiinco
  GOPROXY: file://${{ github.workspace }}/go-modules/public

jobs:
  golang-private-goproxy-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        if: ${{ success() }}
        with:
          go-version: ${{ inputs.go-version }}

      - run: go version
        if: ${{ success() }}

      - name: Grant access to private Go Modules
        if: ${{ success() }}
        run: git config --global url."https://fiinco:${{ secrets.github-token }}@github.com/Fiinco".insteadOf "https://github.com/Fiinco"

      - name: Checkout private goproxy repo
        uses: actions/checkout@v4
        with:
          repository: Fiinco/governance-goproxy
          token: ${{ secrets.github-token }}
          path: go-modules

      #Go libraries can't be built
      - name: Build Application
        #if: ${{ success() && (!startsWith(github.event.repository.name, 'lib-go-')) }}
        if: ${{ success() }}
        run: go build -ldflags="-s -w" -o ./app/ ./...

