name: Golang Check PR Title

#checks PR title to make sure it conforms to release-please format
#PR title should start with one of:
# - 'fix:'
# - 'feat:'
# - 'feat!:'

on:
  workflow_call:

jobs:
  golang-check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR title is not semantic-commit compliant
#        if: >
#          ${{
#          !startsWith(github.event.pull_request.title, 'fix:') &&
#          !startsWith(github.event.pull_request.title, 'feat:') &&
#          !startsWith(github.event.pull_request.title, 'feat!:')
#          }}
        if: >
          ${{ 
          !startsWith(github.event.pull_request.title, 'fix:') 
          }}

        uses: actions/github-script@v7
        with:
          script: | 
            core.setFailed('PR title must start with one of the following: [fix:], [feat:], or [feat!:]')
